inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-performance

AllCops:
  Exclude:
    - examples/**/*
    - script/*
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 20

Layout/LineLength:
  Max: 120
  AllowedPatterns: ['^ *#'] # ignore comments (only ones that take up the whole line)

Metrics/MethodLength:
  Max: 60

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Max: 50
  Exclude:
    - spec/**/*
    - lib/tasks/**/*
  AllowedMethods: ['describe', 'context', 'class_methods']

Metrics/ParameterLists:
  Max: 10

Naming/FileName:
  Exclude:
    - 'lib/search-engine-for-typesense.rb'

Naming/MethodParameterName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/NumericLiterals:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either_consistent

Style/Documentation:
  Exclude:
    - 'script/dev/**/*'
    - 'test/**/*'

Layout/SpaceAroundOperators:
  EnforcedStyleForExponentOperator: space

Layout/HashAlignment:
  Enabled: false

Performance/RedundantMerge:
  MaxKeyValuePairs: 1
