#!/usr/bin/env ruby
# frozen_string_literal: true

begin
  require 'rails'
rescue LoadError
  # If Rails isn't available, the gem will still load; TUI can boot Rails later if present
end

begin
  require 'search_engine'
  require 'search_engine/cli/tuit'
rescue LoadError
  # Allow running from a gem checkout where lib/ isn't on $LOAD_PATH
  $LOAD_PATH.unshift(File.expand_path('../lib', __dir__))
  require 'search_engine'
  require 'search_engine/cli/tuit'
end

exit(SearchEngine::CLI::Tuit.run(ARGV))
